# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveLoadDemo' do
  
  inhibit_all_warnings!
  pod 'LiveLoadClient', :path => '../LiveLoadClient.podspec'

end
